//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asmodat_Web_Exchange {
    
    
    public partial class ExchangeControl {
        
        /// <summary>
        /// AlertsControlPrimary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.AlertsControl AlertsControlPrimary;
        
        /// <summary>
        /// URbtnAssetPrimaryBuy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.UpdateButton URbtnAssetPrimaryBuy;
        
        /// <summary>
        /// URbtnAssetPrimarySell control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.UpdateButton URbtnAssetPrimarySell;
        
        /// <summary>
        /// UTbxAmountPrimary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.UpdateTextBox UTbxAmountPrimary;
        
        /// <summary>
        /// UDdlCurrencyPrimary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.UpdateDropDownList UDdlCurrencyPrimary;
        
        /// <summary>
        /// ULBtnAssetPrimaryGlyph control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.UpdateLabelButton ULBtnAssetPrimaryGlyph;
        
        /// <summary>
        /// AlertsControlSecondary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.AlertsControl AlertsControlSecondary;
        
        /// <summary>
        /// URbtnAssetSecondaryBuy control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.UpdateButton URbtnAssetSecondaryBuy;
        
        /// <summary>
        /// URbtnAssetSecondarySell control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.UpdateButton URbtnAssetSecondarySell;
        
        /// <summary>
        /// UTbxAmountSecondary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.UpdateTextBox UTbxAmountSecondary;
        
        /// <summary>
        /// UDdlCurrencySecondary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.UpdateDropDownList UDdlCurrencySecondary;
        
        /// <summary>
        /// ULBtnAssetSecondaryGlyph control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.UpdateLabelButton ULBtnAssetSecondaryGlyph;
        
        /// <summary>
        /// UpdPnlExchangeControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdPnlExchangeControl;
        
        /// <summary>
        /// TimrExchangeControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.Timer TimrExchangeControl;
    }
}
