//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asmodat_Web_Exchange {
    
    
    public partial class FundingsControl {
        
        /// <summary>
        /// AlertsControlDeposit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.AlertsControl AlertsControlDeposit;
        
        /// <summary>
        /// ULblDeposit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.UpdateLabel ULblDeposit;
        
        /// <summary>
        /// UTbxDeposit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.UpdateTextBox UTbxDeposit;
        
        /// <summary>
        /// UDdlDeposit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.UpdateDropDownList UDdlDeposit;
        
        /// <summary>
        /// AlertsControlWithdraw control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.AlertsControl AlertsControlWithdraw;
        
        /// <summary>
        /// ULblWithdraw control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.UpdateLabel ULblWithdraw;
        
        /// <summary>
        /// UTbxWithdraw control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.UpdateTextBox UTbxWithdraw;
        
        /// <summary>
        /// UDdlWithdraw control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Asmodat_Web_Exchange.UpdateDropDownList UDdlWithdraw;
        
        /// <summary>
        /// UpdPnlFundingControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.UpdatePanel UpdPnlFundingControl;
        
        /// <summary>
        /// TimrFundingsControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.Timer TimrFundingsControl;
    }
}
